import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Nav from './nav/page'
import koderb from '../../assets/imgs/koderblue.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <head>
        <link rel="icon" type="image/png" href="/koderblue.png" />
      </head>
      <html lang="en" className='flex flex-col-reverse'>
        <Nav />
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
